// src/ui/src/features/chat/components/MessageBubble.vue
<script setup lang="ts">
import { computed } from "vue"
import { renderMarkdownToHtml } from "../chatContracts.js"

const props = defineProps<{
  role: "user" | "assistant"
  content: string
}>()

const renderedContent = computed(() => renderMarkdownToHtml(props.content))
</script>

<template>
  <article
    class="max-w-[94%] rounded-2xl px-3 py-2 shadow-sm"
    :class="role === 'user'
      ? 'ml-auto bg-[var(--corvus-user-bubble)] text-[var(--corvus-user-text,var(--corvus-bg))]'
      : 'mr-auto border border-[var(--corvus-border)] bg-[var(--corvus-ai-bubble)] text-[var(--corvus-text)]'"
  >
    <p
      class="mb-1 text-[11px] font-semibold uppercase tracking-[0.14em]"
      :class="role === 'user' ? 'text-[color-mix(in_srgb,var(--corvus-bg)_80%,transparent)]' : 'text-[var(--corvus-text-secondary)]'"
    >
      {{ role === "user" ? "You" : "Assistant" }}
    </p>
    <div class="corvus-markdown text-sm leading-6" v-html="renderedContent" />
  </article>
</template>

<style scoped>
.corvus-markdown :deep(*) {
  word-break: break-word;
}

.corvus-markdown :deep(:first-child) {
  margin-top: 0;
}

.corvus-markdown :deep(:last-child) {
  margin-bottom: 0;
}

.corvus-markdown :deep(code) {
  border-radius: 0.35rem;
  background: color-mix(in srgb, var(--corvus-surface-raised) 84%, transparent);
  padding: 0.12rem 0.35rem;
  font-family: var(--corvus-font-mono);
  font-size: 0.9em;
}

.corvus-markdown :deep(pre) {
  overflow-x: auto;
  border-radius: 0.85rem;
  background: color-mix(in srgb, var(--corvus-surface-raised) 88%, transparent);
  padding: 0.75rem;
}
</style>

// src/ui/src/app/views/chat/message-bubble.component.ts
import { Component, Input } from "@angular/core"
import { CommonModule } from "@angular/common"
import { MarkdownPipe } from "../../shared/pipes/markdown.pipe"

@Component({
  selector: "corvus-message-bubble",
  standalone: true,
  imports: [CommonModule, MarkdownPipe],
  template: `
    <div class="bubble" [class.user]="role === 'user'" [class.assistant]="role === 'assistant'">
      <div class="bubble-label">{{ role === 'user' ? 'You' : 'Assistant' }}</div>
      <div class="bubble-content" [innerHTML]="content | markdown"></div>
    </div>
  `,
  styles: [`
    .bubble {
      padding: 8px 12px;
      border-radius: var(--corvus-radius);
      max-width: 95%;
      word-wrap: break-word;
    }
    .bubble-label {
      font-size: var(--corvus-font-size-sm);
      font-weight: 600;
      margin-bottom: 4px;
      color: var(--corvus-text-secondary);
    }
    .bubble.user {
      background: var(--corvus-user-bubble);
      color: #fff;
      align-self: flex-end;
    }
    .bubble.user .bubble-label {
      color: rgba(255, 255, 255, 0.8);
    }
    .bubble.assistant {
      background: var(--corvus-ai-bubble);
      align-self: flex-start;
    }
    .bubble-content {
      line-height: 1.5;
    }
    .bubble-content :first-child {
      margin-top: 0;
    }
    .bubble-content :last-child {
      margin-bottom: 0;
    }
    .bubble-content code {
      font-family: var(--corvus-font-mono);
      font-size: 0.9em;
      background: rgba(0,0,0,0.06);
      padding: 1px 4px;
      border-radius: 3px;
    }
    .bubble-content pre {
      background: rgba(0,0,0,0.06);
      padding: 8px;
      border-radius: var(--corvus-radius-sm);
      overflow-x: auto;
    }
  `],
})
export class MessageBubbleComponent {
  @Input() role: "user" | "assistant" = "assistant"
  @Input() content = ""
}
